Routing
TimeaUnger/react-mentoring-course pull request #6
Opened 2023-04-20 07:40 UTC by TimeaUnger

2023-04-26 16:35 UTC, Xizi0n requested changes

2023-04-26 16:35 UTC, Xizi0n commented on movies-app/src/components/GenreSelect/GenreSelect.jsx
> +    const selectedGenre = event.target.innerHTML;
Security szempontból szerencsésebb
```suggestion
    const selectedGenre = event.target.innerText;
```

2023-04-26 16:35 UTC, Xizi0n commented on movies-app/src/Helpers/urlHepler.js
> +}
Ez miért kell a useLocation() hookkal egyszerűen megtudod őket kapni.

const { pathname, search} = useLocation();

2023-04-26 16:35 UTC, Xizi0n commented on movies-app/src/components/SortControl/SortControl.jsx
> +  const location = useLocation();
```suggestion
  const { search } = useLocation();
```

2023-04-26 16:35 UTC, Xizi0n commented on movies-app/src/components/SortControl/SortControl.jsx
> +  const [searchParams, setSearchParams] = useSearchParams({});
```suggestion
  const [searchParams, setSearchParams] = useSearchParams();
```

2023-04-26 16:35 UTC, Xizi0n commented on movies-app/src/components/SortControl/SortControl.jsx
> +  const location = useLocation();
Így átláthatóbb lesz

2023-04-26 16:35 UTC, Xizi0n commented on movies-app/src/components/SortControl/SortControl.jsx
> +  const [sortOption, setSortOption] = useState("release_date");
Ez nem lehetne így?
```suggestion
  const [sortBy, setSortBy] = useState(searchParams.get('sortBy') || 'release_date');
```

2023-04-26 16:35 UTC, Xizi0n commented on movies-app/src/components/SortControl/SortControl.jsx
> +  const searchQuery = location.search !== "" ? searchParams.get("search") : "";
Így egyszerűbb lenne szerintem de ugyanúgy lehetne useStatetel mint felette
```suggestion
  const activeGenre =searchParams.get("activeGenre") || "All";
  const searchQuery = searchParams.get("search") || "";
```

2023-04-26 16:35 UTC, Xizi0n commented on movies-app/src/components/SortControl/SortControl.jsx
> +    }
Ezt itt le lehetne egyszerűsíteni ha mindennek van default értéke. ki lehetne hagyni az ifet

2023-04-26 16:35 UTC, Xizi0n commented on movies-app/src/components/SearchForm/SearchForm.jsx
> +  const [searchVal, setSearchVal] = useState("");
Ennek is paramsból kellene inicializálódnia

2023-04-26 16:35 UTC, Xizi0n commented on movies-app/src/components/SearchForm/SearchForm.jsx
> +      });
A hardcodeolt értékek itt szeirntem okozhatnak hibás működést szerintem url param alapján/default value kellene őket beállítna.

Például ha előtte az activeGenre Crime volt akkor hiába nerm változtatta a user mostmár All lesz

2023-04-26 16:35 UTC, Xizi0n commented on movies-app/src/components/SearchForm/SearchForm.jsx
> +    });
Ugyanaz mint az előtinél searchből kellene inicializálódnia

2023-04-26 16:35 UTC, Xizi0n commented on movies-app/src/components/MovieListPage/MovieListPage.jsx
> +  });
ezt itt szerintem üresen kellen meghívni mert ha egy url alapján érkezel az oldalra akkor ezekkel felül fogja írni.

2023-04-26 16:35 UTC, Xizi0n commented on movies-app/src/components/MovieListPage/MovieListPage.jsx
> +  const [searchQuery, setSearchQuery] = useState("");
Ezeket szerinem Paramsból kellene inicializálni

2023-04-26 16:35 UTC, Xizi0n commented on movies-app/src/components/GenreSelect/GenreSelect.jsx
> +  const [searchParams, setSearchParams] = useSearchParams({});
Nem kell inicializálni
```suggestion
  const [searchParams, setSearchParams] = useSearchParams();
```

2023-04-26 16:35 UTC, Xizi0n commented on movies-app/src/components/MovieListPage/MovieListPage.jsx
> +  });
Ez itt miért van hardcodeolva? Miért nincs setter? csak simán useSearchParams() elég lenne

2023-04-27 08:55 UTC, TimeaUnger commented on movies-app/src/components/SortControl/SortControl.jsx
> +  const [sortOption, setSortOption] = useState("release_date");
a useSate() hook ki lett szedve :-)

2023-04-27 08:57 UTC, TimeaUnger commented on movies-app/src/components/SortControl/SortControl.jsx
> +  const searchQuery = location.search !== "" ? searchParams.get("search") : "";
a useSate() logikat kiszedtem, mert reolad-nal az url parametereit kell hasznalnia

2023-04-27 09:07 UTC, TimeaUnger commented on movies-app/src/components/SearchForm/SearchForm.jsx
> +  const [searchVal, setSearchVal] = useState("");
Paramsbol a search value? Itt csak a search action van lekezelve "setSearchParams"-al. A searchVal az input field-bol jon

2023-04-27 09:10 UTC, TimeaUnger commented on movies-app/src/components/SearchForm/SearchForm.jsx
> +      });
Itt szandekosan adtam meg az "All"-t, mert ha keresel filmet, az, amit talalsz, barmilyen genre lehet

2023-04-27 09:13 UTC, TimeaUnger commented on movies-app/src/components/MovieListPage/MovieListPage.jsx
> +  });
Meg kell adni a default erteket, kell az elso load-hoz, mar kiprobaltam. Nem irja ez felul. Ha pl a genre komponensbol inditod a setSearchParams-ot a megadott ertekekkel, az irja felul a default-ot

2023-04-27 09:14 UTC, TimeaUnger commented on movies-app/src/components/MovieListPage/MovieListPage.jsx
> +  const [searchQuery, setSearchQuery] = useState("");
Ez mar nem aktualis, azota lecsereltem :-)

2023-04-27 09:16 UTC, TimeaUnger commented on movies-app/src/components/MovieListPage/MovieListPage.jsx
> +  });
Ez a first load-hoz kell

2023-04-27 09:28 UTC, TimeaUnger commented on movies-app/src/Helpers/urlHepler.js
> +}
Kozben en is rajottem :-D

2023-05-04 06:41 UTC, Xizi0n approved these changes

2023-05-04 06:41 UTC, Xizi0n commented on movies-app/cypress/e2e/MovieListPage.cy.js
> +  });
Így egyszerűbb és kicsit real-use szagú is a történet :) 
cy.get('.movieTilesWrapper a').click().

cy.location(pathname).should('iclude', href)

2023-05-04 06:41 UTC, Xizi0n commented on movies-app/cypress/e2e/MovieListPage.cy.js
> +  });
Itt először rá kellene kattintani nem? 🤔

2023-05-04 06:41 UTC, Xizi0n commented on movies-app/cypress/e2e/MovieListPage.cy.js
> +  });
Nem kell használni az invokeokat, van beépített retry a cypressben nem kell chainelni a promisokat.

Illetve itt is az equal helyett egyszrűbb lehet a contains és akkor nem kell a hosszú urlt kézzel megadni

2023-05-04 06:41 UTC, Xizi0n commented on movies-app/cypress/e2e/MovieListPage.cy.js
> +    cy.location('search').should('equal', '?search=test&searchBy=title&sortBy=release_date&activeGenre=All')
Így egyszerűbb
cy.location('search').should('contain', 'search=test')

2023-05-04 06:45 UTC, Xizi0n commented on movies-app/src/components/SearchForm/SearchForm.jsx
> +      });
Szerintem érdemesebb megtartani a filtereket ilyenkor de elfogadom az érvelést :)

2023-05-04 06:45 UTC, Xizi0n commented
Pár apróság, de egyébként rendben van :)

2023-05-06 15:29 UTC, merged